import type { ApiSourceDefinition } from "@/types/osint";

const GLOBAL = "GLOBAL";
export const PUBLIC_APIS_REGISTRY_URL = "https://github.com/public-apis/public-apis";

const BASE_FREE_API_CATALOG = [
  {
    key: "contracts-finder",
    name: "UK Contracts Finder",
    regions: ["GB"],
    category: "tenders",
    access: "free",
    status: "live",
    url: "https://www.contractsfinder.service.gov.uk/apidocumentation/home",
    notes: "Public procurement notices in OCDS format.",
    mappedConnector: "contracts_finder",
  },
  {
    key: "find-a-tender",
    name: "Find a Tender Service",
    regions: ["GB"],
    category: "tenders",
    access: "free",
    status: "live",
    url: "https://www.find-tender.service.gov.uk/Search",
    notes: "UK higher-value procurement opportunities.",
    mappedConnector: "find_a_tender",
  },
  {
    key: "companies-house",
    name: "UK Companies House API",
    regions: ["GB"],
    category: "company",
    access: "free_tier",
    status: "live",
    url: "https://developer.company-information.service.gov.uk/",
    notes: "Company records, filings, status, incorporation data.",
    mappedConnector: "companies_house",
  },
  {
    key: "planning-data-uk",
    name: "Planning Data (UK)",
    regions: ["GB"],
    category: "planning",
    access: "free",
    status: "live",
    url: "https://www.planning.data.gov.uk/",
    notes: "Planning and development signals for local opportunity discovery.",
    mappedConnector: "planning_portal",
  },
  {
    key: "adzuna",
    name: "Adzuna Jobs API",
    regions: ["GB", "US", "AU", "CA", "DE", "FR", "IN", "NL", "PL", "SG"],
    category: "jobs",
    access: "free_tier",
    status: "live",
    url: "https://developer.adzuna.com/",
    notes: "Job market demand and hiring-intent signals.",
    mappedConnector: "adzuna",
  },
  {
    key: "google-news-rss",
    name: "Google News RSS",
    regions: [GLOBAL],
    category: "news",
    access: "free",
    status: "live",
    url: "https://news.google.com/rss",
    notes: "Public news mentions and trend detection.",
    mappedConnector: "news_rss",
  },
  {
    key: "data-gov-uk",
    name: "UK Government Open Data",
    regions: ["GB"],
    category: "government",
    access: "free",
    status: "planned",
    url: "https://data.gov.uk/",
    notes: "Broad UK open-data catalog for market, policy, and location intelligence.",
  },
  {
    key: "data-gov-us",
    name: "US Government Open Data",
    regions: ["US"],
    category: "government",
    access: "free",
    status: "planned",
    url: "https://www.data.gov/",
    notes: "Federal open-data catalog with broad public-sector coverage.",
  },
  {
    key: "sec-edgar-data",
    name: "SEC EDGAR Data",
    regions: ["US"],
    category: "company",
    access: "free",
    status: "planned",
    url: "https://www.sec.gov/edgar/sec-api-documentation",
    notes: "Public company filings, reports, and disclosure signals.",
  },
  {
    key: "usaspending",
    name: "USAspending.gov",
    regions: ["US"],
    category: "tenders",
    access: "free",
    status: "planned",
    url: "https://api.usaspending.gov/",
    notes: "US federal spending and award data for procurement intelligence.",
  },
  {
    key: "federal-register",
    name: "Federal Register",
    regions: ["US"],
    category: "government",
    access: "free",
    status: "planned",
    url: "https://www.federalregister.gov/reader-aids/developer-resources/rest-api",
    notes: "US regulatory notices and government announcements.",
  },
  {
    key: "usa-jobs",
    name: "USAJOBS",
    regions: ["US"],
    category: "jobs",
    access: "free_tier",
    status: "planned",
    url: "https://developer.usajobs.gov/",
    notes: "US government job board and hiring signals.",
  },
  {
    key: "data-parliament-uk",
    name: "UK Parliament Data",
    regions: ["GB"],
    category: "government",
    access: "free",
    status: "planned",
    url: "https://explore.data.parliament.uk/",
    notes: "Bills, petitions, votes, and parliamentary activity.",
  },
  {
    key: "ons-api",
    name: "UK ONS API",
    regions: ["GB"],
    category: "research",
    access: "free",
    status: "planned",
    url: "https://developer.ons.gov.uk/",
    notes: "Official UK economic and demographic statistics for market context.",
  },
  {
    key: "police-uk-api",
    name: "Police UK API",
    regions: ["GB"],
    category: "government",
    access: "free",
    status: "planned",
    url: "https://data.police.uk/docs/",
    notes: "Street-level crime and policing outcomes by location.",
  },
  {
    key: "uk-food-standards-agency",
    name: "UK Food Standards Agency Open Data",
    regions: ["GB"],
    category: "government",
    access: "free",
    status: "planned",
    url: "http://ratings.food.gov.uk/open-data/en-GB",
    notes: "Food hygiene ratings and venue compliance signals.",
  },
  {
    key: "uk-legal-changes",
    name: "UK Legislation Changes",
    regions: ["GB"],
    category: "government",
    access: "free",
    status: "planned",
    url: "https://uk-legal-changes.pages.dev/docs",
    notes: "Point-in-time amendment tracking for UK law and regulatory monitoring.",
  },
  {
    key: "uk-environment-flood-monitoring",
    name: "UK Environment Agency Flood Monitoring",
    regions: ["GB"],
    category: "government",
    access: "free",
    status: "planned",
    url: "https://environment.data.gov.uk/flood-monitoring/doc/reference",
    notes: "Flood and environmental alerts useful for local risk overlays.",
  },
  {
    key: "uk-land-registry-price-paid",
    name: "UK Land Registry Price Paid Data",
    regions: ["GB"],
    category: "open_data",
    access: "free",
    status: "planned",
    url: "https://landregistry.data.gov.uk/app/ppd/",
    notes: "Property transaction prices and local market movement signals.",
  },
  {
    key: "uk-national-archives-api",
    name: "UK National Archives API",
    regions: ["GB"],
    category: "government",
    access: "free",
    status: "planned",
    url: "https://api.nationalarchives.gov.uk/",
    notes: "Government records discovery for policy and institution monitoring.",
  },
  {
    key: "nhs-scotland-open-data",
    name: "NHS Scotland Open Data",
    regions: ["GB"],
    category: "open_data",
    access: "free",
    status: "planned",
    url: "https://www.opendata.nhs.scot/",
    notes: "Health service reference statistics and public-service demand signals.",
  },
  {
    key: "uk-gazette-data",
    name: "UK Gazette Data",
    regions: ["GB"],
    category: "government",
    access: "free_tier",
    status: "planned",
    url: "https://www.thegazette.co.uk/data",
    notes: "Official UK public record and notice data.",
  },
  {
    key: "open-corporates",
    name: "OpenCorporates",
    regions: [GLOBAL],
    category: "company",
    access: "free_tier",
    status: "planned",
    url: "https://api.opencorporates.com/documentation/API-Reference",
    notes: "Cross-jurisdiction company and director data.",
  },
  {
    key: "open-sanctions",
    name: "OpenSanctions",
    regions: [GLOBAL],
    category: "risk",
    access: "free",
    status: "planned",
    url: "https://www.opensanctions.org/docs/api/",
    notes: "Sanctions, PEP, and adverse media screening.",
  },
  {
    key: "publicdatahub",
    name: "PublicDataHub",
    regions: ["US"],
    category: "open_data",
    access: "free",
    status: "planned",
    url: "https://publicdatahub.org/api",
    notes: "Public schools, hospitals, and agency budgets with provenance.",
  },
  {
    key: "eu-tenders-bidledger",
    name: "Bidledger EU Tenders",
    regions: ["EU"],
    category: "tenders",
    access: "free",
    status: "planned",
    url: "https://jaydemks.github.io/bidledger/api.html",
    notes: "Daily rebuilt public EU tender feed from official TED data.",
  },
  {
    key: "world-bank",
    name: "World Bank Open Data API",
    regions: [GLOBAL],
    category: "research",
    access: "free",
    status: "planned",
    url: "https://datahelpdesk.worldbank.org/knowledgebase/articles/889392",
    notes: "Economic context by country for macro trend overlays.",
  },
  {
    key: "openalex",
    name: "OpenAlex API",
    regions: [GLOBAL],
    category: "research",
    access: "free",
    status: "planned",
    url: "https://docs.openalex.org/",
    notes: "Research and innovation signals for deep-tech markets.",
  },
  {
    key: "eu-ted",
    name: "EU Tenders Electronic Daily (TED)",
    regions: ["EU"],
    category: "tenders",
    access: "free",
    status: "planned",
    url: "https://ted.europa.eu/",
    notes: "EU procurement coverage for cross-border expansion.",
  },
  {
    key: "us-sec-edgar",
    name: "US SEC EDGAR",
    regions: ["US"],
    category: "company",
    access: "free",
    status: "planned",
    url: "https://www.sec.gov/edgar/search/",
    notes: "Filings and disclosures as enterprise buying signals.",
  },
  {
    key: "india-mca",
    name: "India MCA public filings",
    regions: ["IN"],
    category: "company",
    access: "free",
    status: "planned",
    url: "https://www.mca.gov.in/",
    notes: "India corporate event monitoring coverage.",
  },
  {
    key: "nigeria-bpp",
    name: "Nigeria BPP procurement portal",
    regions: ["NG"],
    category: "tenders",
    access: "free",
    status: "planned",
    url: "https://bpp.gov.ng/",
    notes: "Public-sector opportunity detection for Nigeria.",
  },
  {
    key: "australia-abn",
    name: "Australia ABN lookup datasets",
    regions: ["AU"],
    category: "company",
    access: "free",
    status: "planned",
    url: "https://abr.business.gov.au/",
    notes: "Business entity and registration signals in Australia.",
  },
  {
    key: "canada-open-canada-procurement",
    name: "Canada Open Procurement Datasets",
    regions: ["CA"],
    category: "tenders",
    access: "free",
    status: "planned",
    url: "https://open.canada.ca/",
    notes: "Federal open data opportunities and contract trends.",
  },
] satisfies Array<Omit<ApiSourceDefinition, "registry">>;

export const FREE_API_CATALOG: ApiSourceDefinition[] = BASE_FREE_API_CATALOG.map((source) => ({
  ...source,
  registry: "public-apis",
}));

export function catalogForRegions(regions: string[]): ApiSourceDefinition[] {
  const normalized = regions.map((item) => item.toUpperCase());
  return FREE_API_CATALOG.filter((source) =>
    source.regions.includes(GLOBAL) || source.regions.some((region) => normalized.includes(region)),
  );
}

export function ukStarterCatalog(): ApiSourceDefinition[] {
  return FREE_API_CATALOG.filter((source) => source.regions.includes("GB") || source.regions.includes(GLOBAL));
}
