import type { ApiSourceDefinition } from "@/types/osint";

const GLOBAL = "GLOBAL";

export const FREE_API_CATALOG: ApiSourceDefinition[] = [
  {
    key: "contracts-finder",
    name: "UK Contracts Finder",
    regions: ["GB"],
    category: "tenders",
    access: "free",
    status: "live",
    url: "https://www.contractsfinder.service.gov.uk/apidocumentation/home",
    notes: "Public procurement notices in OCDS format.",
    mappedConnector: "contracts_finder",
  },
  {
    key: "find-a-tender",
    name: "Find a Tender Service",
    regions: ["GB"],
    category: "tenders",
    access: "free",
    status: "live",
    url: "https://www.find-tender.service.gov.uk/Search",
    notes: "UK higher-value procurement opportunities.",
    mappedConnector: "find_a_tender",
  },
  {
    key: "companies-house",
    name: "UK Companies House API",
    regions: ["GB"],
    category: "company",
    access: "free_tier",
    status: "live",
    url: "https://developer.company-information.service.gov.uk/",
    notes: "Company records, filings, status, incorporation data.",
    mappedConnector: "companies_house",
  },
  {
    key: "planning-data-uk",
    name: "Planning Data (UK)",
    regions: ["GB"],
    category: "planning",
    access: "free",
    status: "live",
    url: "https://www.planning.data.gov.uk/",
    notes: "Planning and development signals for local opportunity discovery.",
    mappedConnector: "planning_portal",
  },
  {
    key: "adzuna",
    name: "Adzuna Jobs API",
    regions: ["GB", "US", "AU", "CA", "DE", "FR", "IN", "NL", "PL", "SG"],
    category: "jobs",
    access: "free_tier",
    status: "live",
    url: "https://developer.adzuna.com/",
    notes: "Job market demand and hiring-intent signals.",
    mappedConnector: "adzuna",
  },
  {
    key: "google-news-rss",
    name: "Google News RSS",
    regions: [GLOBAL],
    category: "news",
    access: "free",
    status: "live",
    url: "https://news.google.com/rss",
    notes: "Public news mentions and trend detection.",
    mappedConnector: "news_rss",
  },
  {
    key: "world-bank",
    name: "World Bank Open Data API",
    regions: [GLOBAL],
    category: "research",
    access: "free",
    status: "planned",
    url: "https://datahelpdesk.worldbank.org/knowledgebase/articles/889392",
    notes: "Economic context by country for macro trend overlays.",
  },
  {
    key: "openalex",
    name: "OpenAlex API",
    regions: [GLOBAL],
    category: "research",
    access: "free",
    status: "planned",
    url: "https://docs.openalex.org/",
    notes: "Research and innovation signals for deep-tech markets.",
  },
  {
    key: "eu-ted",
    name: "EU Tenders Electronic Daily (TED)",
    regions: ["EU"],
    category: "tenders",
    access: "free",
    status: "planned",
    url: "https://ted.europa.eu/",
    notes: "EU procurement coverage for cross-border expansion.",
  },
  {
    key: "us-sec-edgar",
    name: "US SEC EDGAR",
    regions: ["US"],
    category: "company",
    access: "free",
    status: "planned",
    url: "https://www.sec.gov/edgar/search/",
    notes: "Filings and disclosures as enterprise buying signals.",
  },
  {
    key: "india-mca",
    name: "India MCA public filings",
    regions: ["IN"],
    category: "company",
    access: "free",
    status: "planned",
    url: "https://www.mca.gov.in/",
    notes: "India corporate event monitoring coverage.",
  },
  {
    key: "nigeria-bpp",
    name: "Nigeria BPP procurement portal",
    regions: ["NG"],
    category: "tenders",
    access: "free",
    status: "planned",
    url: "https://bpp.gov.ng/",
    notes: "Public-sector opportunity detection for Nigeria.",
  },
  {
    key: "australia-abn",
    name: "Australia ABN lookup datasets",
    regions: ["AU"],
    category: "company",
    access: "free",
    status: "planned",
    url: "https://abr.business.gov.au/",
    notes: "Business entity and registration signals in Australia.",
  },
  {
    key: "canada-open-canada-procurement",
    name: "Canada Open Procurement Datasets",
    regions: ["CA"],
    category: "tenders",
    access: "free",
    status: "planned",
    url: "https://open.canada.ca/",
    notes: "Federal open data opportunities and contract trends.",
  },
];

export function catalogForRegions(regions: string[]): ApiSourceDefinition[] {
  const normalized = regions.map((item) => item.toUpperCase());
  return FREE_API_CATALOG.filter((source) =>
    source.regions.includes(GLOBAL) || source.regions.some((region) => normalized.includes(region)),
  );
}
