import type { ApiSourceDefinition } from "@/types/osint";

const GLOBAL = "GLOBAL";
export const PUBLIC_APIS_REGISTRY_URL = "https://github.com/public-apis/public-apis";

const BASE_FREE_API_CATALOG = [
  {
    key: "contracts-finder",
    name: "UK Contracts Finder",
    regions: ["GB"],
    category: "tenders",
    access: "free",
    status: "live",
    url: "https://www.contractsfinder.service.gov.uk/apidocumentation/home",
    notes: "Public procurement notices in OCDS format.",
    mappedConnector: "contracts_finder",
  },
  {
    key: "find-a-tender",
    name: "Find a Tender Service",
    regions: ["GB"],
    category: "tenders",
    access: "free",
    status: "live",
    url: "https://www.find-tender.service.gov.uk/Search",
    notes: "UK higher-value procurement opportunities.",
    mappedConnector: "find_a_tender",
  },
  {
    key: "companies-house",
    name: "UK Companies House API",
    regions: ["GB"],
    category: "company",
    access: "free_tier",
    status: "live",
    url: "https://developer.company-information.service.gov.uk/",
    notes: "Company records, filings, status, incorporation data.",
    mappedConnector: "companies_house",
  },
  {
    key: "planning-data-uk",
    name: "Planning Data (UK)",
    regions: ["GB"],
    category: "planning",
    access: "free",
    status: "live",
    url: "https://www.planning.data.gov.uk/",
    notes: "Planning and development signals for local opportunity discovery.",
    mappedConnector: "planning_portal",
  },
  {
    key: "adzuna",
    name: "Adzuna Jobs API",
    regions: ["GB", "US", "AU", "CA", "DE", "FR", "IN", "NL", "PL", "SG"],
    category: "jobs",
    access: "free_tier",
    status: "live",
    url: "https://developer.adzuna.com/",
    notes: "Job market demand and hiring-intent signals.",
    mappedConnector: "adzuna",
  },
  {
    key: "google-news-rss",
    name: "Google News RSS",
    regions: [GLOBAL],
    category: "news",
    access: "free",
    status: "live",
    url: "https://news.google.com/rss",
    notes: "Public news mentions and trend detection.",
    mappedConnector: "news_rss",
  },
  {
    key: "noozra",
    name: "Noozra",
    regions: [GLOBAL],
    category: "news",
    access: "free",
    status: "live",
    url: "https://noozra.com/api",
    notes: "Free news headlines aggregated from 200+ curated RSS sources.",
  },
  {
    key: "the-guardian",
    name: "The Guardian Open Platform",
    regions: [GLOBAL],
    category: "news",
    access: "free_tier",
    status: "live",
    url: "http://open-platform.theguardian.com/",
    notes: "News content and metadata for narrative momentum and topical monitoring.",
  },
  {
    key: "spaceflight-news",
    name: "Spaceflight News",
    regions: [GLOBAL],
    category: "news",
    access: "free",
    status: "live",
    url: "https://spaceflightnewsapi.net",
    notes: "Space-related news for niche market and technology trend signals.",
    mappedConnector: "spaceflight_news",
  },
  {
    key: "data-gov-uk",
    name: "UK Government Open Data",
    regions: ["GB"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://data.gov.uk/",
    notes: "Broad UK open-data catalog for market, policy, and location intelligence.",
  },
  {
    key: "data-parliament-uk",
    name: "UK Parliament Data",
    regions: ["GB"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://explore.data.parliament.uk/",
    notes: "Bills, petitions, votes, attendance and parliamentary activity.",
  },
  {
    key: "uk-federal-contracts-grants",
    name: "US Federal Contracts & Grants",
    regions: ["US"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://government-data-api.onrender.com/docs",
    notes: "US federal contracts, grants and agency spending data updated daily.",
  },
  {
    key: "data-gov-us",
    name: "US Government Open Data",
    regions: ["US"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://www.data.gov/",
    notes: "Federal open-data catalog with broad public-sector coverage.",
  },
  {
    key: "open-government-australia",
    name: "Open Government, Australia",
    regions: ["AU"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://www.data.gov.au/",
    notes: "Australian Government Open Data.",
  },
  {
    key: "open-government-austria",
    name: "Open Government, Austria",
    regions: ["EU"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://www.data.gv.at/",
    notes: "Austria Government Open Data.",
  },
  {
    key: "open-government-belgium",
    name: "Open Government, Belgium",
    regions: ["EU"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://data.gov.be/",
    notes: "Belgium Government Open Data.",
  },
  {
    key: "open-government-canada",
    name: "Open Government, Canada",
    regions: ["CA"],
    category: "government",
    access: "free",
    status: "live",
    url: "http://open.canada.ca/en",
    notes: "Canadian Government Open Data.",
  },
  {
    key: "open-government-cyprus",
    name: "Open Government, Cyprus",
    regions: ["EU"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://data.gov.cy/?language=en",
    notes: "Cyprus Government Open Data.",
  },
  {
    key: "open-government-czech-republic",
    name: "Open Government, Czech Republic",
    regions: ["EU"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://data.gov.cz/english/",
    notes: "Czech Republic Government Open Data.",
  },
  {
    key: "open-government-denmark",
    name: "Open Government, Denmark",
    regions: ["EU"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://www.opendata.dk/",
    notes: "Denmark Government Open Data.",
  },
  {
    key: "open-government-estonia",
    name: "Open Government, Estonia",
    regions: ["EU"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://avaandmed.eesti.ee/instructions/opendata-dataset-api",
    notes: "Estonia Government Open Data.",
  },
  {
    key: "open-government-finland",
    name: "Open Government, Finland",
    regions: ["EU"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://www.avoindata.fi/en",
    notes: "Finland Government Open Data.",
  },
  {
    key: "open-government-france",
    name: "Open Government, France",
    regions: ["EU"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://www.data.gouv.fr/",
    notes: "French Government Open Data.",
  },
  {
    key: "open-government-germany",
    name: "Open Government, Germany",
    regions: ["EU"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://www.govdata.de/daten/-/details/govdata-metadatenkatalog",
    notes: "Germany Government Open Data.",
  },
  {
    key: "open-government-greece",
    name: "Open Government, Greece",
    regions: ["EU"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://data.gov.gr/",
    notes: "Greece Government Open Data.",
  },
  {
    key: "open-government-india",
    name: "Open Government, India",
    regions: ["IN"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://data.gov.in/",
    notes: "Indian Government Open Data.",
  },
  {
    key: "open-government-indonesia",
    name: "Open Government, Indonesia",
    regions: ["AS"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://data.go.id/",
    notes: "Indonesian Government Open Data.",
  },
  {
    key: "open-government-ireland",
    name: "Open Government, Ireland",
    regions: ["EU"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://data.gov.ie/pages/developers",
    notes: "Ireland Government Open Data.",
  },
  {
    key: "open-government-italy",
    name: "Open Government, Italy",
    regions: ["EU"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://www.dati.gov.it/",
    notes: "Italy Government Open Data.",
  },
  {
    key: "open-government-korea",
    name: "Open Government, Korea",
    regions: ["AS"],
    category: "government",
    access: "free_tier",
    status: "live",
    url: "https://www.data.go.kr/",
    notes: "Korea Government Open Data.",
  },
  {
    key: "open-government-lithuania",
    name: "Open Government, Lithuania",
    regions: ["EU"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://data.gov.lt/public/api/1",
    notes: "Lithuania Government Open Data.",
  },
  {
    key: "open-government-luxembourg",
    name: "Open Government, Luxembourg",
    regions: ["EU"],
    category: "government",
    access: "free_tier",
    status: "live",
    url: "https://data.public.lu",
    notes: "Luxembourgish Government Open Data.",
  },
  {
    key: "open-government-mexico",
    name: "Open Government, Mexico",
    regions: ["NA"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://datos.gob.mx/",
    notes: "Mexico Government Open Data.",
  },
  {
    key: "open-government-netherlands",
    name: "Open Government, Netherlands",
    regions: ["EU"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://data.overheid.nl/en/ondersteuning/data-publiceren/api",
    notes: "Netherlands Government Open Data.",
  },
  {
    key: "open-government-new-south-wales",
    name: "Open Government, New South Wales",
    regions: ["AU"],
    category: "government",
    access: "free_tier",
    status: "live",
    url: "https://api.nsw.gov.au/",
    notes: "New South Wales Government Open Data.",
  },
  {
    key: "open-government-new-zealand",
    name: "Open Government, New Zealand",
    regions: ["OC"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://www.data.govt.nz/",
    notes: "New Zealand Government Open Data.",
  },
  {
    key: "open-government-norway",
    name: "Open Government, Norway",
    regions: ["EU"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://data.norge.no/dataservices",
    notes: "Norwegian Government Open Data.",
  },
  {
    key: "open-government-peru",
    name: "Open Government, Peru",
    regions: ["SA"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://www.datosabiertos.gob.pe/",
    notes: "Peru Government Open Data.",
  },
  {
    key: "open-government-poland",
    name: "Open Government, Poland",
    regions: ["EU"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://dane.gov.pl/en",
    notes: "Poland Government Open Data.",
  },
  {
    key: "open-government-portugal",
    name: "Open Government, Portugal",
    regions: ["EU"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://dados.gov.pt/en/docapi/",
    notes: "Portugal Government Open Data.",
  },
  {
    key: "open-government-queensland",
    name: "Open Government, Queensland Government",
    regions: ["AU"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://www.data.qld.gov.au/",
    notes: "Queensland Government Open Data.",
  },
  {
    key: "open-government-saudi-arabia",
    name: "Open Government, Saudi Arabia",
    regions: ["AS"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://data.gov.sa",
    notes: "Saudi Arabia Government Open Data.",
  },
  {
    key: "open-government-singapore",
    name: "Open Government, Singapore",
    regions: ["AS"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://data.gov.sg/developer",
    notes: "Singapore Government Open Data.",
  },
  {
    key: "open-government-slovakia",
    name: "Open Government, Slovakia",
    regions: ["EU"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://data.gov.sk/en/",
    notes: "Slovakia Government Open Data.",
  },
  {
    key: "open-government-slovenia",
    name: "Open Government, Slovenia",
    regions: ["EU"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://podatki.gov.si/",
    notes: "Slovenia Government Open Data.",
  },
  {
    key: "open-government-south-australia",
    name: "Open Government, South Australian Government",
    regions: ["AU"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://data.sa.gov.au/",
    notes: "South Australian Government Open Data.",
  },
  {
    key: "open-government-spain",
    name: "Open Government, Spain",
    regions: ["EU"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://datos.gob.es/en",
    notes: "Spain Government Open Data.",
  },
  {
    key: "open-government-sweden",
    name: "Open Government, Sweden",
    regions: ["EU"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://www.dataportal.se/en/dataservice/91_29789/api-for-the-statistical-database",
    notes: "Sweden Government Open Data.",
  },
  {
    key: "open-government-switzerland",
    name: "Open Government, Switzerland",
    regions: ["EU"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://handbook.opendata.swiss/de/content/nutzen/api-nutzen.html",
    notes: "Switzerland Government Open Data.",
  },
  {
    key: "open-government-taiwan",
    name: "Open Government, Taiwan",
    regions: ["AS"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://data.gov.tw/",
    notes: "Taiwan Government Open Data.",
  },
  {
    key: "open-government-thailand",
    name: "Open Government, Thailand",
    regions: ["AS"],
    category: "government",
    access: "free_tier",
    status: "live",
    url: "https://data.go.th/",
    notes: "Thailand Government Open Data.",
  },
  {
    key: "open-government-victoria",
    name: "Open Government, Victoria State Government",
    regions: ["AU"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://www.data.vic.gov.au/",
    notes: "Victoria State Government Open Data.",
  },
  {
    key: "open-government-west-australia",
    name: "Open Government, West Australia",
    regions: ["AU"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://data.wa.gov.au/",
    notes: "West Australia Open Data.",
  },
  {
    key: "city-new-york-open-data",
    name: "City, New York Open Data",
    regions: ["US"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://opendata.cityofnewyork.us/",
    notes: "New York City open datasets including crime, GIS and finance.",
  },
  {
    key: "city-toronto-open-data",
    name: "City, Toronto Open Data",
    regions: ["CA"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://open.toronto.ca/",
    notes: "Toronto open data for city-level intelligence.",
  },
  {
    key: "colorado-information-marketplace",
    name: "Colorado Information Marketplace",
    regions: ["US"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://data.colorado.gov/",
    notes: "Colorado state open data.",
  },
  {
    key: "district-of-columbia-open-data",
    name: "District of Columbia Open Data",
    regions: ["US"],
    category: "government",
    access: "free",
    status: "live",
    url: "http://opendata.dc.gov/pages/using-apis",
    notes: "D.C. government public datasets including crime, GIS and financial data.",
  },
  {
    key: "data-usa",
    name: "Data USA",
    regions: ["US"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://datausa.io/about/api/",
    notes: "US public data and demographics.",
  },
  {
    key: "federal-register-live",
    name: "Federal Register",
    regions: ["US"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://www.federalregister.gov/reader-aids/developer-resources/rest-api",
    notes: "US daily journal of government notices.",
  },
  {
    key: "uk-bank-holidays-live",
    name: "UK Bank Holidays",
    regions: ["GB"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://www.gov.uk/bank-holidays.json",
    notes: "UK bank holiday calendar.",
  },
  {
    key: "uk-bank-holidays",
    name: "UK Bank Holidays",
    regions: ["GB"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://www.gov.uk/bank-holidays.json",
    notes: "Public holiday calendar useful for regional scheduling and timing.",
    mappedConnector: "uk_bank_holidays",
  },
  {
    key: "usa-gov",
    name: "USA.gov Developer API",
    regions: ["US"],
    category: "government",
    access: "free_tier",
    status: "live",
    url: "https://www.usa.gov/developer",
    notes: "Authoritative information on U.S. programs, events and services.",
  },
  {
    key: "sec-edgar-data",
    name: "SEC EDGAR Data",
    regions: ["US"],
    category: "company",
    access: "free",
    status: "planned",
    url: "https://www.sec.gov/edgar/sec-api-documentation",
    notes: "Public company filings, reports, and disclosure signals.",
  },
  {
    key: "funding-signals",
    name: "Funding Signals",
    regions: [GLOBAL],
    category: "company",
    access: "free_tier",
    status: "live",
    url: "https://fundingsignals.net/docs",
    notes: "Companies that raised funding, scored as sales leads from public SEC filings.",
  },
  {
    key: "globalentity",
    name: "GlobalEntity",
    regions: ["EU"],
    category: "company",
    access: "free_tier",
    status: "live",
    url: "https://www.globalentityapi.com/docs",
    notes: "Official company data from European business registers.",
  },
  {
    key: "katalis-uk-company-enrichment",
    name: "Katalis UK Company Enrichment",
    regions: ["GB"],
    category: "company",
    access: "free_tier",
    status: "live",
    url: "https://meetkatalis.com/apis",
    notes: "Verified UK company profiles with AI summaries and accuracy scores.",
  },
  {
    key: "registrum",
    name: "Registrum",
    regions: ["GB"],
    category: "company",
    access: "free_tier",
    status: "live",
    url: "https://api.registrum.co.uk/docs",
    notes: "UK company data including profiles, directors, PSC and financials.",
  },
  {
    key: "openregistry",
    name: "OpenRegistry",
    regions: [GLOBAL],
    category: "company",
    access: "free_tier",
    status: "live",
    url: "https://openregistry.sophymarine.com",
    notes: "Queries to national company registries across multiple countries.",
  },
  {
    key: "openmercantil",
    name: "OpenMercantil",
    regions: ["EU"],
    category: "company",
    access: "free",
    status: "live",
    url: "https://openmercantil.es/api/documentacion",
    notes: "Spanish company public data and BORME event timelines.",
  },
  {
    key: "tradedatahub",
    name: "TradeDataHub",
    regions: ["US"],
    category: "company",
    access: "free",
    status: "live",
    url: "https://www.tradedatahub.net",
    notes: "U.S. contractor datasets with discovery coverage and masked previews.",
  },
  {
    key: "usaspending",
    name: "USAspending.gov",
    regions: ["US"],
    category: "tenders",
    access: "free",
    status: "live",
    url: "https://api.usaspending.gov/",
    notes: "US federal spending and award data for procurement intelligence.",
  },
  {
    key: "us-federal-contracts-grants",
    name: "US Federal Contracts & Grants API",
    regions: ["US"],
    category: "tenders",
    access: "free",
    status: "live",
    url: "https://government-data-api.onrender.com/docs",
    notes: "Daily updated US federal contracts, grants and agency spending data.",
  },
  {
    key: "bidledger",
    name: "Bidledger EU Tenders",
    regions: ["EU"],
    category: "tenders",
    access: "free",
    status: "live",
    url: "https://jaydemks.github.io/bidledger/api.html",
    notes: "Rebuilt daily from official TED data for EU procurement intelligence.",
  },
  {
    key: "tenders-ukraine",
    name: "Tenders in Ukraine",
    regions: ["EU"],
    category: "tenders",
    access: "free",
    status: "live",
    url: "https://tenders.guru/ua/api",
    notes: "Public procurement data for Ukraine.",
  },
  {
    key: "federal-register",
    name: "Federal Register",
    regions: ["US"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://www.federalregister.gov/reader-aids/developer-resources/rest-api",
    notes: "US regulatory notices and government announcements.",
    mappedConnector: "federal_register",
  },
  {
    key: "usa-jobs",
    name: "USAJOBS",
    regions: ["US"],
    category: "jobs",
    access: "free_tier",
    status: "planned",
    url: "https://developer.usajobs.gov/",
    notes: "US government job board and hiring signals.",
  },
  {
    key: "ai-dev-jobs",
    name: "AI Dev Jobs",
    regions: [GLOBAL],
    category: "jobs",
    access: "free",
    status: "live",
    url: "https://aidevboard.com/openapi.yaml",
    notes: "AI/ML engineering job aggregator with REST, RSS and MCP endpoints.",
  },
  {
    key: "devitjobs-uk",
    name: "DevITjobs UK",
    regions: ["GB"],
    category: "jobs",
    access: "free",
    status: "live",
    url: "https://devitjobs.uk/job_feed.xml",
    notes: "UK tech jobs feed via XML and GraphQL-style integrations.",
  },
  {
    key: "freehire",
    name: "freehire",
    regions: [GLOBAL],
    category: "jobs",
    access: "free",
    status: "live",
    url: "https://freehire.dev/docs/api",
    notes: "Open-source search engine aggregating tech jobs from ATS boards.",
  },
  {
    key: "jobven",
    name: "Jobven",
    regions: [GLOBAL],
    category: "jobs",
    access: "free_tier",
    status: "live",
    url: "https://jobven.com/docs/getting-started",
    notes: "Jobs tracked as roles open and close with change webhooks.",
  },
  {
    key: "jobspipe",
    name: "JobsPipe",
    regions: [GLOBAL],
    category: "jobs",
    access: "free_tier",
    status: "live",
    url: "https://docs.jobspipe.dev",
    notes: "Live job postings from ATS feeds and boards in one normalized schema.",
  },
  {
    key: "data-parliament-uk",
    name: "UK Parliament Data",
    regions: ["GB"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://explore.data.parliament.uk/",
    notes: "Bills, petitions, votes, and parliamentary activity.",
  },
  {
    key: "ons-api",
    name: "UK ONS API",
    regions: ["GB"],
    category: "research",
    access: "free",
    status: "live",
    url: "https://developer.ons.gov.uk/",
    notes: "Official UK economic and demographic statistics for market context.",
  },
  {
    key: "police-uk-api",
    name: "Police UK API",
    regions: ["GB"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://data.police.uk/docs/",
    notes: "Street-level crime and policing outcomes by location.",
  },
  {
    key: "uk-food-standards-agency",
    name: "UK Food Standards Agency Open Data",
    regions: ["GB"],
    category: "government",
    access: "free",
    status: "live",
    url: "http://ratings.food.gov.uk/open-data/en-GB",
    notes: "Food hygiene ratings and venue compliance signals.",
  },
  {
    key: "uk-legal-changes",
    name: "UK Legislation Changes",
    regions: ["GB"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://uk-legal-changes.pages.dev/docs",
    notes: "Point-in-time amendment tracking for UK law and regulatory monitoring.",
  },
  {
    key: "uk-environment-flood-monitoring",
    name: "UK Environment Agency Flood Monitoring",
    regions: ["GB"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://environment.data.gov.uk/flood-monitoring/doc/reference",
    notes: "Flood and environmental alerts useful for local risk overlays.",
  },
  {
    key: "uk-land-registry-price-paid",
    name: "UK Land Registry Price Paid Data",
    regions: ["GB"],
    category: "open_data",
    access: "free",
    status: "live",
    url: "https://landregistry.data.gov.uk/app/ppd/",
    notes: "Property transaction prices and local market movement signals.",
  },
  {
    key: "uk-national-archives-api",
    name: "UK National Archives API",
    regions: ["GB"],
    category: "government",
    access: "free",
    status: "live",
    url: "https://api.nationalarchives.gov.uk/",
    notes: "Government records discovery for policy and institution monitoring.",
  },
  {
    key: "nhs-scotland-open-data",
    name: "NHS Scotland Open Data",
    regions: ["GB"],
    category: "open_data",
    access: "free",
    status: "live",
    url: "https://www.opendata.nhs.scot/",
    notes: "Health service reference statistics and public-service demand signals.",
  },
  {
    key: "govuk-news-rss",
    name: "GOV.UK News RSS",
    regions: ["GB"],
    category: "news",
    access: "free",
    status: "live",
    url: "https://www.gov.uk/search/news-and-communications.atom",
    notes: "Official government communications and policy updates via RSS/Atom.",
    mappedConnector: "govuk_news_rss",
  },
  {
    key: "bbc-news-rss",
    name: "BBC News RSS",
    regions: [GLOBAL],
    category: "news",
    access: "free",
    status: "live",
    url: "https://feeds.bbci.co.uk/news/rss.xml",
    notes: "General news momentum and narrative shift detection.",
    mappedConnector: "bbc_news_rss",
  },
  {
    key: "world-bank-news",
    name: "World Bank News and Data",
    regions: [GLOBAL],
    category: "research",
    access: "free",
    status: "live",
    url: "https://datahelpdesk.worldbank.org/knowledgebase/articles/889392",
    notes: "Open macro context for international market shifts.",
    mappedConnector: "world_bank",
  },
  {
    key: "uk-gazette-data",
    name: "UK Gazette Data",
    regions: ["GB"],
    category: "government",
    access: "free_tier",
    status: "planned",
    url: "https://www.thegazette.co.uk/data",
    notes: "Official UK public record and notice data.",
  },
  {
    key: "open-corporates",
    name: "OpenCorporates",
    regions: [GLOBAL],
    category: "company",
    access: "free_tier",
    status: "live",
    url: "https://api.opencorporates.com/documentation/API-Reference",
    notes: "Cross-jurisdiction company and director data.",
  },
  {
    key: "open-sanctions",
    name: "OpenSanctions",
    regions: [GLOBAL],
    category: "risk",
    access: "free",
    status: "live",
    url: "https://www.opensanctions.org/docs/api/",
    notes: "Sanctions, PEP, and adverse media screening.",
  },
  {
    key: "publicdatahub",
    name: "PublicDataHub",
    regions: ["US"],
    category: "open_data",
    access: "free",
    status: "planned",
    url: "https://publicdatahub.org/api",
    notes: "Public schools, hospitals, and agency budgets with provenance.",
  },
  {
    key: "eu-tenders-bidledger",
    name: "Bidledger EU Tenders",
    regions: ["EU"],
    category: "tenders",
    access: "free",
    status: "live",
    url: "https://jaydemks.github.io/bidledger/api.html",
    notes: "Daily rebuilt public EU tender feed from official TED data.",
  },
  {
    key: "world-bank",
    name: "World Bank Open Data API",
    regions: [GLOBAL],
    category: "research",
    access: "free",
    status: "live",
    url: "https://datahelpdesk.worldbank.org/knowledgebase/articles/889392",
    notes: "Economic context by country for macro trend overlays.",
  },
  {
    key: "openalex",
    name: "OpenAlex API",
    regions: [GLOBAL],
    category: "research",
    access: "free",
    status: "live",
    url: "https://docs.openalex.org/",
    notes: "Research and innovation signals for deep-tech markets.",
  },
  {
    key: "eu-ted",
    name: "EU Tenders Electronic Daily (TED)",
    regions: ["EU"],
    category: "tenders",
    access: "free",
    status: "live",
    url: "https://ted.europa.eu/",
    notes: "EU procurement coverage for cross-border expansion.",
  },
  {
    key: "us-sec-edgar",
    name: "US SEC EDGAR",
    regions: ["US"],
    category: "company",
    access: "free",
    status: "live",
    url: "https://www.sec.gov/edgar/search/",
    notes: "Filings and disclosures as enterprise buying signals.",
  },
  {
    key: "india-mca",
    name: "India MCA public filings",
    regions: ["IN"],
    category: "company",
    access: "free",
    status: "planned",
    url: "https://www.mca.gov.in/",
    notes: "India corporate event monitoring coverage.",
  },
  {
    key: "nigeria-bpp",
    name: "Nigeria BPP procurement portal",
    regions: ["NG"],
    category: "tenders",
    access: "free",
    status: "planned",
    url: "https://bpp.gov.ng/",
    notes: "Public-sector opportunity detection for Nigeria.",
  },
  {
    key: "australia-abn",
    name: "Australia ABN lookup datasets",
    regions: ["AU"],
    category: "company",
    access: "free",
    status: "live",
    url: "https://abr.business.gov.au/",
    notes: "Business entity and registration signals in Australia.",
  },
  {
    key: "canada-open-canada-procurement",
    name: "Canada Open Procurement Datasets",
    regions: ["CA"],
    category: "tenders",
    access: "free",
    status: "live",
    url: "https://open.canada.ca/",
    notes: "Federal open data opportunities and contract trends.",
  },
] satisfies Array<Omit<ApiSourceDefinition, "registry">>;

export const FREE_API_CATALOG: ApiSourceDefinition[] = BASE_FREE_API_CATALOG.map((source) => ({
  ...source,
  registry: "public-apis",
}));

export function catalogForRegions(regions: string[]): ApiSourceDefinition[] {
  const normalized = regions.map((item) => item.toUpperCase());
  return FREE_API_CATALOG.filter((source) =>
    source.regions.includes(GLOBAL) || source.regions.some((region) => normalized.includes(region)),
  );
}

export function ukStarterCatalog(): ApiSourceDefinition[] {
  return FREE_API_CATALOG.filter((source) => source.regions.includes("GB") || source.regions.includes(GLOBAL));
}
